### PR TITLE
Service test: Servo

### PR DESCRIPTION
**Pull request by pelikhan**
attempt at servo tests

### CODE REVIEW

**Comment by pelikhan** [comment]
@tballmsft we need a way to assign a value to a register and observe the changes.

**Comment by tballmsft** [comment]
we have assign(register, expression) - everything is a function call right now.

**Review by tballmsft — COMMENTED** [review]
try this

**Comment by pelikhan** [comment]
Crashes UI
image

**Comment by tballmsft** [comment]
oh, that's interesting... let me take a look.

**Comment by tballmsft** [comment]
Fixed.

**Pull request merged**
