### PR TITLE
Device: JM Pressure Sensor v1.0

### PR DESCRIPTION
**Pull request by milador**
This pull request registers a new device for Jacdac.

### CODE REVIEW

**Comment by pelikhan** [comment]
@milador could you run `make bump` in your repo to create a binary release of your firmware?

> Use `make bump` to create a new release. This will ask you for a version number (providing a default that just updates the patch number), update CHANGES.md, create a git tag, and push it to the origin.

**Comment by milador** [comment]
@pelikhan I am making updated boards that look better in 2 weeks. I modified my current module for debugging purposes and added jumpers. Lets wait till then so I take better pictures.

I ran `make bump` and get following error when it tries to create the tag which seems to be related to my setup:

`RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (node:internal/errors:371:5)
    at Socket.onChildStdout (node:child_process:459:14)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
  cmd: 'git log --submodule=log --oneline --patch --decorate=full '
}`

Any idea or suggestion? Thanks

**Comment by pelikhan** [comment]
@mmoskal have you seen this before?

**Comment by mmoskal** [comment]
never seen it; what version of node.js do you have?

**Comment by milador** [comment]
Can it be my jacdac-stm32x0 setup? I forked it instead of using it as submodule.

**Comment by milador** [comment]
@pelikhan and @mmoskal : I increased the buffer size ( doubled it ) and it solved the issue. Now it's complaining about submodule jacdac-c which I modified to add additional driver as I added it manually. What is the best way to do this? I am thinking to make a Pull request to original jacdac-c repository to add the driver first.

**Comment by mmoskal** [comment]
@milador PR on jacdac-c is definitely preferred, so other people can benefit from your driver

otherwise, you can just place your driver in addons/ folder of your forked repo

**Comment by milador** [comment]
@mmoskal Okay great. I do it the proper way then. Other people can use it as well. Thanks

**Comment by milador** [comment]
@pelikhan and @mmoskal it worked without the need to modify the buffer size. And here's the [CHANGES.md](https://github.com/milador/jacdac-milador-modules/blob/main/CHANGES.md)

**Review by mmoskal — APPROVED** [review]
@pelikhan I think this is good to merge?

**Comment by pelikhan** [comment]
yup

**Pull request merged**
