### PR TITLE
Spec revisions

### PR DESCRIPTION
**Pull request by jamesadevine**

### CODE REVIEW

**Comment by jamesadevine** [comment]
Where should "device identifiers" live?

**Comment by jamesadevine** [comment]
Perhaps we need a devices page... We could include all the info about adding devices to the repository there too?

**Comment by pelikhan** [comment]
We have a devices page in jacdac-ts... you can leave it as a separate file for now IMO and we'll update everything later on.

**Comment by tballmsft** [comment]
We need to mention explicitly that the protocol does not do anything about allocation of device identifiers and have a little bit about it. The HDK needs to have a page about generating device identifiers, for sure.

**Pull request merged**
