### PR TITLE
Device: Calliope mini 3

### PR DESCRIPTION
**Pull request by joernalraun**
This pull request will start the registration of your device in the Jacdac catalog.

### CODE REVIEW

**Comment by joernalraun** [comment]
> @joernalraun please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
@microsoft-github-policy-service agree [company="{Calliope gGmbH}"]

**Comment by pelikhan** [comment]
@joernalraun  Do you have more info about the USB connection? See the microbit device config.

https://github.com/microsoft/jacdac/blob/main/devices/microbit-educational-foundation/microbitv2.json

**Comment by pelikhan** [comment]
The picture looks a bit dark maybe? https://microsoft.github.io/jacdac-docs/devices/calliope-ggmbh/calliopeminiv3v30/

**Comment by joernalraun** [comment]
> The picture looks a bit dark maybe? https://microsoft.github.io/jacdac-docs/devices/calliope-ggmbh/calliopeminiv3v30/

I think it is ok, the pcb is now black/dark gray matte. ;)

**Comment by joernalraun** [comment]
> @joernalraun Do you have more info about the USB connection? See the microbit device config.
> 
> https://github.com/microsoft/jacdac/blob/main/devices/microbit-educational-foundation/microbitv2.json

USB is "Calliope mini V3 CMSIS-DAP".
So this would be:

  "transport": {
    "type": "usb",
    "requestDescription": "Calliope mini V3 CMSIS-DAP"
  }

I think! :)

**Comment by pelikhan** [comment]
It would be good to also have a build of the "jukebox" for calliope.

**Comment by joernalraun** [comment]
> It would be good to also have a build of the "jukebox" for calliope.

Yes, sounds good to me as well. We will look into this!

**Pull request merged**
