### PR TITLE
Add hold to button spec

### PR DESCRIPTION
**Pull request by jamesadevine**

### CODE REVIEW

**Comment by jamesadevine** [comment]
why do up/down appear at 0x1/0x2, but click, long click, and hold come at 0x8N?

**Comment by pelikhan** [comment]
down/up map to reserved event code active/inactive

**Comment by jamesadevine** [comment]
Got it... so presumably the hold button code needs to be a different value?

**Comment by pelikhan** [comment]
Looks good

**Review by mmoskal — APPROVED** [review]

**Pull request merged**
