### PR TITLE
Service test: Compass

### PR DESCRIPTION
**Pull request by pelikhan**
attempt at creating a compass test

### CODE REVIEW

**Comment by pelikhan** [comment]
@tballmsft we need an operator to be "close to..." and probably module is the compass is near 360/0.

**Comment by mmoskal** [comment]
I guess `check((0 <= heading && heading <= 10) || (350 <= heading && heading < 360))` ?

**Comment by pelikhan** [comment]
We need a shorthand operator to deal with noisy data, something like « close to ( a,b) «

________________________________

**Comment by tballmsft** [comment]
Yes, this makes sense. I'll work on it this week.

**Comment by pelikhan** [comment]
close to (actual, expected, error)

________________________________

**Comment by tballmsft** [comment]
closeTo is now implemented (see potentiometer.md).

**Review by tballmsft — COMMENTED** [review]
I've implemented closeTo. Please give it a try.

**Pull request merged**
