### PR TITLE
client/server flags

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Review by mmoskal — COMMENTED** [review]
not a great fan of `server` wording; I like `lowlevel` more

**Comment by mmoskal** [comment]
also client/server wording suggests it either one or the other, while most of our regs/cmds are none.

Interestingly, it's possible to think of a low-level client thing (used to implement higher-level client things). Then we would have to say `client server ro foobar`...

**Comment by pelikhan** [comment]
ok for lowlevel. how about "metal"?

**Comment by mmoskal** [comment]
metal better than server, but I think lowlevel is way more descriptive

**Pull request merged**
